apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-spi
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
binaryData:
  spi_temis_grupos-1.0.0.jar: |-
    {{ .Files.Get "spi/spi_temis_grupos-1.0.0.jar" | b64enc | indent 4 }}
