apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-spi
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
binaryData: 
  ojdbc8-23.2.0.0.jar: |-
    {{ .Files.Get "spi/ojdbc8-23.2.0.0.jar" | b64enc | indent 4 }}
